#!/usr/bin/env python
"""Usage: collect-tweets -q QUERY_TERM -c MONGO_COLLECTION_NAME

-h --help    show this
-q, --query QUERY_TERM  the search term for the twitter stream filter
-c --mongo_collection_name the name of the mongo collection to store the tweets in

"""
import os
import sys
import signal
from time import sleep
from multiprocessing import Pool
from twitter_stream import TwitterStream
from mongo_twitter_consumer import MongoTwitterConsumer
from docopt import docopt

if __name__ == '__main__':
    QUERY_ARG = '--query'
    COLL_NAME = '--mongo_collection_name'

    args = docopt(__doc__, argv=None, help=True, version=None, options_first=False)

    query_term = args[QUERY_ARG]
    coll_name = args[COLL_NAME]

    twitter_stream = TwitterStream(query_term)
    mongo_consumer = MongoTwitterConsumer(coll_name)

    try:
        twitter_stream.start()

        # Wait for twitter stream to start.
        print('twitter stream is alive', twitter_stream.process.is_alive())
        while not twitter_stream.process.is_alive():
            print('waiting for twitter stream', flush=True)
            sleep(500)

        mongo_consumer.start(twitter_stream.stream_name)

        while True:
            pass

    except KeyboardInterrupt:
        print("Caught KeyboardInterrupt, terminating stream.")
        mongo_consumer.stop()
        twitter_stream.stop()
        twitter_stream.destroy()
        print("Bye!")


